common_packages:
  - screen
  - git
  - dnsutils
  - binutils
  - keepassxc
  - python3-gpg
  - tcpdump
  - xca
  - qemu
  - qemu-kvm
  - libvirt-daemon
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - apt-transport-https
  - debsums
  - apt-show-versions

rsnapshot_backups:
  src_paths:
    - "/home/{{ lookup('env', 'USER') }}/"
    - '/etc/'
    - '/var/log/audit/'
    - '/var/lib/aide/aide.db'
  snapshot_root: "/media/exthdd/backups"
