- name: Copy issue and issue.net content
  ansible.builtin.copy:
    content: "{{ etc_issue_and_issue_net_content }}"
    dest: "{{ issue_file }}"
  become: yes
  loop:
    - /etc/issue
    - /etc/issue.net
  loop_control:
    loop_var: issue_file

- name: Disable core dumps
  lineinfile:
    path: /etc/security/limits.conf
    line: '* hard core 0'
  become: yes

- name: Ensure cron.deny is missing
  file:
    path: /etc/cron.deny
    state: absent
  become: yes

- name: Ensure cron.allow exists
  file:
    path: /etc/cron.allow
    mode: 0644
    owner: root
    group: root
    state: touch
  become: yes

- name: Set recommended values for login.defs
  lineinfile:
    path: /etc/login.defs
    regexp: '{{ current_umask_value[0] }}'
    line: '{{ current_umask_value[1] }}'
  become: yes
  loop:
    - ['^PASS_MAX_DAYS.*', 'PASS_MAX_DAYS   365']
    - ['^UMASK.*', 'UMASK           027']
    - ['^PASS_MIN_DAYS.*', 'PASS_MIN_DAYS   1']
  loop_control:
    loop_var: current_umask_value

- name: Find all home directories
  find:
    paths: /home/
    recurse: no
    file_type: directory
  register: dirs

- name: Set home dir permissions
  file:
    path: "{{ current_home.path }}"
    mode: 0750
  loop: "{{ dirs['files'] }}"
  loop_control:
    loop_var: current_home
