---
- name: Harden kernel parameters
  ansible.posix.sysctl:
    name: "{{ current_param }}"
    value: "{{ hardened_kernel_params[current_param] }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ hardened_kernel_params }}"
  loop_control:
    loop_var: current_param
  become: yes

- name: Add /bin/true to disable kernel module installs
  copy:
    dest: "{{ current_item['path'] }}"
    content: "{{ current_item['line'] }}"
  become: yes
  loop: "{{ modpobe_disable }}"
  loop_control:
    loop_var: current_item

- name: Ensure unneeded kernel modules are disabled
  community.general.modprobe:
    name: "{{ current_module['line'].split()[1] }}"
    state: absent
  become: yes
  loop: "{{ modpobe_disable }}"
  loop_control:
    loop_var: current_module
