hardened_kernel_params:
  fs.suid_dumpable: "0"
  fs.protected_fifos: "2"
  fs.protected_hardlinks: "1"
  fs.protected_regular: "2"
  fs.protected_symlinks: "1"
  kernel.core_uses_pid: "1"
  kernel.ctrl-alt-del: "0"
  kernel.dmesg_restrict: "1"
  kernel.kptr_restrict: "2"
  kernel.perf_event_paranoid: "3"
  kernel.randomize_va_space: "2"
  kernel.sysrq: "0"
  kernel.unprivileged_bpf_disabled: "1"
  kernel.yama.ptrace_scope: "2"
  net.core.bpf_jit_harden: "2"
  net.ipv4.conf.all.accept_redirects: "0"
  net.ipv4.conf.all.accept_source_route: "0"
  net.ipv4.conf.all.bootp_relay: "0"
  net.ipv4.conf.all.forwarding: "0"
  net.ipv4.conf.all.log_martians: "1"
  net.ipv4.conf.all.proxy_arp: "0"
  net.ipv4.conf.all.rp_filter: "1"
  net.ipv4.conf.all.send_redirects: "0"
  net.ipv4.conf.default.accept_redirects: "0"
  net.ipv4.conf.default.accept_source_route: "0"
  net.ipv4.conf.default.log_martians: "1"
  net.ipv4.icmp_echo_ignore_broadcasts: "1"
  net.ipv4.icmp_ignore_bogus_error_responses: "1"
  net.ipv4.tcp_syncookies: "1"
  net.ipv4.tcp_timestamps: "1"
  dev.tty.ldisc_autoload: "0"

etc_issue_and_issue_net_content: "no unauthorized usage"
systemd_services_to_stop_and_disable:
  - 'postfix.service'
  - 'avahi-daemon.service'
  - 'bluetooth.service'
  - 'cockpit.service'
  - 'cockpit-wsinstance-http-redirect.service'
  - 'cockpit-wsinstance-http.service'
  - 'cups-browsed.service'
  - 'cups.service'
  - 'rsync.service'
  - 'sshd.service'
  - 'ssh.service'
  - 'libvirtd.serve'

ufw:
  policy_out: allow
  tcp_allow_out:
  - '80'
  - '443'
  - '53'
  - '22'
  udp_allow_out:
  - '123'
  - '53'
  - '67'
  - '68'

systemd_unit_files_to_harden:
  - path: /lib/systemd/system/unattended-upgrades.service
    lines:
      - 'PrivateDevices=yes'
      - 'ProtectControlGroups=yes'
      - 'ProtectHome=yes'
      - 'ProtectKernelTunables=yes'
      - 'ProtectKernelModules=yes'
      - 'ProtectSystem=yes'
      - 'RestrictSUIDSGID=yes'
      - 'ProtectHostname=yes'
      - 'PrivateTmp=yes'
      - 'UMask=0077'
      - 'MemoryDenyWriteExecute=yes'
      - 'RestrictAddressFamilies=~AF_NETLINK AF_PACKET'
      - 'CapabilityBoundingSet=~CAP_MKNOD CAP_KILL CAP_SYSLOG CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW CAP_LINUX_IMMUTABLE CAP_IPC_LOCK CAP_SYS_CHROOT CAP_BLOCK_SUSPEND CAP_LEASE CAP_SYS_PACCT CAP_SYS_TTY_CONFI GAP_WAKE_ALARM CAP_SYS_TTY_CONFIG CAP_WAKE_ALARM CAP_SYS_BOOT CAP_NET_ADMIN'
      - 'RestrictNamespaces=yes'
      - 'SystemCallFilter=~@clock @debug @obsolete @swap @resources'
      - 'NoNewPrivileges=yes'
  - path: /lib/systemd/system/clamav-freshclam.service
    lines:
      - 'PrivateDevices=yes'
      - 'ProtectControlGroups=yes'
      - 'ProtectHome=yes'
      - 'ProtectKernelTunables=yes'
      - 'ProtectKernelModules=yes'
      - 'ProtectSystem=yes'
      - 'RestrictSUIDSGID=yes'
      - 'ProtectHostname=yes'
      - 'PrivateTmp=yes'
      - 'UMask=0077'
      - 'MemoryDenyWriteExecute=yes'
      - 'RestrictAddressFamilies=~AF_NETLINK AF_PACKET AF_UNIX'
      - 'CapabilityBoundingSet=~CAP_MKNOD CAP_KILL CAP_SYSLOG CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW CAP_LINUX_IMMUTABLE CAP_IPC_LOCK CAP_SYS_CHROOT CAP_BLOCK_SUSPEND CAP_LEASE CAP_SYS_PACCT CAP_SYS_TTY_CONFI GAP_WAKE_ALARM CAP_SYS_TTY_CONFIG CAP_WAKE_ALARM CAP_SYS_BOOT CAP_SYS_PTRACE CAP_SYS_PTRACE CAP_SETPCAP CAP_MAC_ADMIN'
      - 'RestrictNamespaces=yes'
      - 'SystemCallFilter=~@clock @debug @obsolete @swap @resources @module @reboot @raw-io @mount'
      - 'NoNewPrivileges=yes'

file_permissions:
   - path: /etc/cron.daily
     mode: '700'
     state: directory
   - path: /etc/cron.d
     mode: '700'
     state: directory
   - path: /etc/cron.hourly
     mode: '700'
     state: directory
   - path: /etc/cron.weekly
     mode: '700'
     state: directory
   - path: /etc/cron.monthly
     mode: '700'
     state: directory
   - path: /etc/sudoers.d
     mode: '700'
     state: directory
   - path: /boot/grub/grub.cfg
     mode: '600'
     state: file
   - path: /etc/cron.allow
     mode: '600'
     state: file
   - path: /etc/crontab
     mode: '600'
     state: file
access_conf_content: |
  +:root:LOCAL
  +:{{ lookup('env', 'USER') }}:LOCAL
  -:ALL:ALL

apparmor:
  packages:
    - apparmor
    - apparmor-utils
    - apparmor-profiles
    - apparmor-profiles-extra
  extra_profiles_path: '/usr/share/apparmor/extra-profiles/'
  # List of extra profiles to enforce
  extra_profiles_enforce:
    - bin.netstat
    - sbin.dhclient
    - sbin.dhclient-script
    - usr.bin.apropos
    - usr.bin.man
    - usr.bin.passwd
    - usr.lib.man-db.man
    - usr.sbin.postalias
    - usr.sbin.postdrop
    - usr.sbin.postmap
    - usr.sbin.postqueue
    - usr.sbin.sendmail
    - usr.sbin.useradd
    - usr.sbin.userdel
  # Keep profiles in complain mode
  complain_profiles: []
  # Custom profiles to copy from templates
  custom_profile_templates:
    - 'apparmor/usr.sbin.wpa_supplicant.j2'

# TODO: document below vars
login_defs_setting_lines:
  - ['^PASS_MAX_DAYS.*', 'PASS_MAX_DAYS   365']
  - ['^UMASK.*', 'UMASK           027']
  - ['^PASS_MIN_DAYS.*', 'PASS_MIN_DAYS   1']

modpobe_disable:
  - path: /etc/modprobe.d/cramfs.conf
    line: 'install cramfs /bin/true'
  - path: /etc/modprobe.d/freevxfs.conf
    line: 'install freevxfs /bin/true'
  - path: /etc/modprobe.d/jffs2.conf
    line: 'install jffs2 /bin/true'
  - path: /etc/modprobe.d/hfs.conf
    line: 'install /bin/true'
  - path: /etc/modprobe.d/hfsplus.conf
    line: 'install hfsplus /bin/true'
  - path: /etc/modprobe.d/udf.conf
    line: 'install udf /bin/true'
  - path: /etc/modprobe.d/dccp.conf
    line: 'install dccp /bin/true'
  - path: /etc/modprobe.d/sctp.conf
    line: 'install sctp /bin/true'
  - path: /etc/modprobe.d/rds.conf
    line: 'install rds /bin/true'
  - path: /etc/modprobe.d/tipc.conf
    line: 'install tipc /bin/true'

aide_monitor_paths:
  - '/etc Full'
  - '/usr/local/sbin Full'
  - '/usr/local/bin Full'
  - '/usr/sbin Full'
  - '/usr/bin/sbin Full'
  - '/bin Full'
  - '/lib Full'
  - '/opt Full'
  - '/snap/bin Full'
  - "{{ lookup('env', 'HOME') }}/.bashrc Full"
  - "{{ lookup('env', 'HOME') }}/.ssh Full"
  - "{{ lookup('env', 'HOME') }}/.config/autostart Full"

